name: destini_challenge_starting
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"  # Cập nhật để hỗ trợ null safety

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  # Phiên bản mới nhất hỗ trợ null safety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
